### PR TITLE
Focus Search Bar and Primary Text Input

### LINKED ISSUE #86: Autofocus on text fields for all components
Requesting an autofocus feature on the text fields/areas for all the components.

### PR DESCRIPTION
**Pull request by y0tik**
fixes #86 

#### This PR is UX Enhancement
- Focuses the searchBar(on desktop) when on "/"
- Re-focuses the primary text input on each page, below are the list of pages with changes:
  - /base64
  - /hash-generator
  - /json-converter
  - /json-formatter
  - /jwt-debugger
  - /markdown-preview
  - /sql-formatter
  - /unix-date-converter
  - /url-parser

Request, maybe we can add this to contribution guideline, to always focus the primary input mode which will allow devs to use there beloved `crtl+A` `crtl+V`

Just a quick note, I have "Prettier" installed, which has reformatted each file that I have worked on.

### CODE REVIEW

**Comment by vaibhav-kaushal** [comment]
@y0tik - This is a _noisy_ Pull Request. For example, all the `'` (single quotes) have been replaced by `"` double quotes. It serves no semantic purpose but just creates a large diff which is difficult to review. In addition, we have a lot of 2 spaces (`  `) converted to 4 spaces (`    `). Again, does not add any value and makes it really difficult to review the actual changes.

I know you have said that you have prettier installed and it has done those changes but I think Prettier does have options around those changes (using single quotes or double quotes, number of spaces for indentations in code format) or wrap single-parameter arrow functions inside parentheses or not! Please, please set those options properly.

@HariKrishna-28 Can we set a default linter format for these stuff so that we have a universal formatting? Maybe inside the `.vscode` directory or something? Or if we can use eslinter, then a config for that maybe?

**Comment by HariKrishna-28** [comment]
> @HariKrishna-28 Can we set a default linter format for these stuff so that we have a universal formatting? Maybe inside the `.vscode` directory or something? Or if we can use eslinter, then a config for that maybe?

We could set up a default format or create a separate `.prettierrc` file.

**Comment by vaibhav-kaushal** [comment]
> We could set up a default format or create a separate `.prettierrc` file.

That would be lovely!

**Comment by y0tik** [comment]
Converting ' to " will only add to uniformity

The best will be to add a config file first with the decided rules. Also we can add a github action to auto format, so as to accommodate people who do not use 'format on save' or uses other plugins to format there code

**Comment by vaibhav-kaushal** [comment]
> Converting ' to " will only add to uniformity
> 
> The best will be to add a config file first with the decided rules. Also we can add a github action to auto format, so as to accommodate people who do not use 'format on save' or uses other plugins to format there code

@HariKrishna-28 is working on that from what I know. We will set those and a prettierrc file so that formatting stays uniform. Hold on for some time @y0tik ! :-)

**Review by HariKrishna-28 — APPROVED** [review]
Looks good to me. Great job!

**Pull request merged**
